
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlqrnhpvqhdyjhskydck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFscXJuaHB2cWhkeWpoc2t5ZGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzOTAyNjUsImV4cCI6MjA1Njk2NjI2NX0.XAB7GLROZZCEKz5K9UkPOMpIwJSGZIRdiqJLwyI6dwk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Initialize realtime subscriptions
(async () => {
  await supabase.removeAllChannels();
})();

// Define the HotelInfo interface to use throughout the app
export interface HotelInfo {
  id: string;
  name: string;
  tagline: string;
  checkout_time: string;
  breakfast_time: string;
  wifi_code: string;
  pool_hours: string;
  updated_at?: string;
}
